name: STAGE BUILD

on:
      workflow_call:
jobs:
  init:
    runs-on: ubuntu-latest
    name: Stage Build
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - run: npm install
   
    - name: build
      run: |
          npm run build  
          
    - name: Create ZIP deployment package
      run: cd dist;zip ../dist.zip * -r  
      
    - uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: dist.zip  