name: STAGE DEPLOY

on:
    workflow_call:
      secrets:
        AWS_ACCESS_KEY_ID:
          required: true  
        SECRET_ACCESS_KEY:
          required: true     
env:
  APP_ID: d3qp3lfgf2c69x
  REPONAME: frontend-bootcamp
  BRANCH_NAME: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
    steps:
    - uses: actions/checkout@v3

    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:  
        name: node-app
   
    - name: Upload S3
      run:  aws s3 cp dist.zip s3://${{ env.REPONAME }}
    
    - name: Make executeable
      run: chmod +x ./.github/scripts/amplify-deploy.sh     

    - name: Deploy
      run:  ./.github/scripts/amplify-deploy.sh 