name: PIPELINE TELCO 2022                              # workflow name

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true  
      SECRET_ACCESS_KEY:
        required: true 
      SNYK_TOKEN:
        required: true
      GITGUARDIAN_API_KEY:
        required: true        
  push:
    branches: [ master ]
jobs:

  init:
    uses: ./.github/workflows/init-test.yml

  security-sast:
    uses: ./.github/workflows/security-sast.yml
    needs: init
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  build:
    uses: ./.github/workflows/build.yml
    needs: [security-sast]

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: [build]
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  
  notification:
    needs: [deploy]
    uses: ./.github/workflows/notification.yml  

  security-dast:
    needs: [deploy]
    uses: ./.github/workflows/security-dast.yml

