name: PIPELINE TELCO 2022                              # workflow name

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true  
      SECRET_ACCESS_KEY:
        required: true   
  push:
    branches: [ master ]
jobs:

  init:
    uses: ./.github/workflows/init-test.yml

  security-sast:
    uses: ./.github/workflows/security-sast.yml
    needs: init

  build:
    uses: ./.github/workflows/build.yml
    needs: [init,security-sast]

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: [init,security-sast,build]
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

  security-dast:
    needs: [init,security-sast,build,deploy]
    uses: ./.github/workflows/security-dast.yml
    # secrets:
    #   GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}

  notification:
    needs: security-dast
    uses: ./.github/workflows/notification.yml  