name: STAGE SECURITY SAST

on:
  workflow_call:

jobs:
  SECRET:
    runs-on: ubuntu-latest
    name: Secret-Scanner
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Secret Detection
        uses: zricethezav/gitleaks-action@master
        continue-on-error: true 

  SAST:
    runs-on: ubuntu-latest
    name: Static-Vulnerability-Scanner
    steps:
      - uses: actions/checkout@v3
      - name: SAST
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        continue-on-error: true 
        with:
          args: '. --sarif --output results.sarif || true'
